<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "publicaciones_unal"
 *
 * Auto generated by Extension Builder 2018-06-15
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Publicaciones UNAL',
    'description' => 'Extension que permite mostrar publicaciones de una dependencia',
    'category' => 'plugin',
    'author' => 'Alexis Ortiz',
    'author_email' => 'eaortiz@unal.edu.co',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '1',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.6.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
